// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.whypulse.why_pulse.modelruntime

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ModelRuntimeApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class InferenceRuntime(val raw: Int) {
  PHONE_MED_GEMMA(0),
  DEVELOPMENT_MACHINE(1),
  DETERMINISTIC(2);

  companion object {
    fun ofRaw(raw: Int): InferenceRuntime? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplorerRequest (
  val schemaVersion: String,
  val evidenceVersion: String,
  val analysisVersion: Long,
  val promptVersion: Long,
  val eventSummariesJson: String,
  val availableCategoryIds: List<String>,
  val availableInfluenceIds: List<String>,
  val allowedOperations: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplorerRequest {
      val schemaVersion = pigeonVar_list[0] as String
      val evidenceVersion = pigeonVar_list[1] as String
      val analysisVersion = pigeonVar_list[2] as Long
      val promptVersion = pigeonVar_list[3] as Long
      val eventSummariesJson = pigeonVar_list[4] as String
      val availableCategoryIds = pigeonVar_list[5] as List<String>
      val availableInfluenceIds = pigeonVar_list[6] as List<String>
      val allowedOperations = pigeonVar_list[7] as List<String>
      return ExplorerRequest(schemaVersion, evidenceVersion, analysisVersion, promptVersion, eventSummariesJson, availableCategoryIds, availableInfluenceIds, allowedOperations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      schemaVersion,
      evidenceVersion,
      analysisVersion,
      promptVersion,
      eventSummariesJson,
      availableCategoryIds,
      availableInfluenceIds,
      allowedOperations,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExplorerRequest
    return ModelRuntimeApiPigeonUtils.deepEquals(this.schemaVersion, other.schemaVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.evidenceVersion, other.evidenceVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.analysisVersion, other.analysisVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.promptVersion, other.promptVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.eventSummariesJson, other.eventSummariesJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.availableCategoryIds, other.availableCategoryIds) && ModelRuntimeApiPigeonUtils.deepEquals(this.availableInfluenceIds, other.availableInfluenceIds) && ModelRuntimeApiPigeonUtils.deepEquals(this.allowedOperations, other.allowedOperations)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.schemaVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.evidenceVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.analysisVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.promptVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.eventSummariesJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.availableCategoryIds)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.availableInfluenceIds)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.allowedOperations)
    return result
  }
  override fun toString(): String {
    return "ExplorerRequest(schemaVersion=$schemaVersion, evidenceVersion=$evidenceVersion, analysisVersion=$analysisVersion, promptVersion=$promptVersion, eventSummariesJson=$eventSummariesJson, availableCategoryIds=$availableCategoryIds, availableInfluenceIds=$availableInfluenceIds, allowedOperations=$allowedOperations)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplorerDecision (
  val operation: String,
  val categoryId: String? = null,
  val influenceIds: List<String>,
  val evidenceVersion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplorerDecision {
      val operation = pigeonVar_list[0] as String
      val categoryId = pigeonVar_list[1] as String?
      val influenceIds = pigeonVar_list[2] as List<String>
      val evidenceVersion = pigeonVar_list[3] as String
      return ExplorerDecision(operation, categoryId, influenceIds, evidenceVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      operation,
      categoryId,
      influenceIds,
      evidenceVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExplorerDecision
    return ModelRuntimeApiPigeonUtils.deepEquals(this.operation, other.operation) && ModelRuntimeApiPigeonUtils.deepEquals(this.categoryId, other.categoryId) && ModelRuntimeApiPigeonUtils.deepEquals(this.influenceIds, other.influenceIds) && ModelRuntimeApiPigeonUtils.deepEquals(this.evidenceVersion, other.evidenceVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.operation)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.categoryId)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.influenceIds)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.evidenceVersion)
    return result
  }
  override fun toString(): String {
    return "ExplorerDecision(operation=$operation, categoryId=$categoryId, influenceIds=$influenceIds, evidenceVersion=$evidenceVersion)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplainerRequest (
  val schemaVersion: String,
  val evidenceVersion: String,
  val findingState: String,
  val metricsJson: String,
  val promotionGatesJson: String,
  val exclusionsJson: String,
  val counterevidenceJson: String,
  val unresolvedInfluencesJson: String,
  val approvedNextObservations: List<String>,
  val askIntent: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplainerRequest {
      val schemaVersion = pigeonVar_list[0] as String
      val evidenceVersion = pigeonVar_list[1] as String
      val findingState = pigeonVar_list[2] as String
      val metricsJson = pigeonVar_list[3] as String
      val promotionGatesJson = pigeonVar_list[4] as String
      val exclusionsJson = pigeonVar_list[5] as String
      val counterevidenceJson = pigeonVar_list[6] as String
      val unresolvedInfluencesJson = pigeonVar_list[7] as String
      val approvedNextObservations = pigeonVar_list[8] as List<String>
      val askIntent = pigeonVar_list[9] as String
      return ExplainerRequest(schemaVersion, evidenceVersion, findingState, metricsJson, promotionGatesJson, exclusionsJson, counterevidenceJson, unresolvedInfluencesJson, approvedNextObservations, askIntent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      schemaVersion,
      evidenceVersion,
      findingState,
      metricsJson,
      promotionGatesJson,
      exclusionsJson,
      counterevidenceJson,
      unresolvedInfluencesJson,
      approvedNextObservations,
      askIntent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExplainerRequest
    return ModelRuntimeApiPigeonUtils.deepEquals(this.schemaVersion, other.schemaVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.evidenceVersion, other.evidenceVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.findingState, other.findingState) && ModelRuntimeApiPigeonUtils.deepEquals(this.metricsJson, other.metricsJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.promotionGatesJson, other.promotionGatesJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.exclusionsJson, other.exclusionsJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.counterevidenceJson, other.counterevidenceJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.unresolvedInfluencesJson, other.unresolvedInfluencesJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.approvedNextObservations, other.approvedNextObservations) && ModelRuntimeApiPigeonUtils.deepEquals(this.askIntent, other.askIntent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.schemaVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.evidenceVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.findingState)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.metricsJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.promotionGatesJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.exclusionsJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.counterevidenceJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.unresolvedInfluencesJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.approvedNextObservations)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.askIntent)
    return result
  }
  override fun toString(): String {
    return "ExplainerRequest(schemaVersion=$schemaVersion, evidenceVersion=$evidenceVersion, findingState=$findingState, metricsJson=$metricsJson, promotionGatesJson=$promotionGatesJson, exclusionsJson=$exclusionsJson, counterevidenceJson=$counterevidenceJson, unresolvedInfluencesJson=$unresolvedInfluencesJson, approvedNextObservations=$approvedNextObservations, askIntent=$askIntent)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExplainerOutput (
  val summary: String,
  val citedParagraphsJson: String,
  val uncertainty: String,
  val citedUnresolvedInfluences: List<String>,
  val approvedNextObservation: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExplainerOutput {
      val summary = pigeonVar_list[0] as String
      val citedParagraphsJson = pigeonVar_list[1] as String
      val uncertainty = pigeonVar_list[2] as String
      val citedUnresolvedInfluences = pigeonVar_list[3] as List<String>
      val approvedNextObservation = pigeonVar_list[4] as String?
      return ExplainerOutput(summary, citedParagraphsJson, uncertainty, citedUnresolvedInfluences, approvedNextObservation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      summary,
      citedParagraphsJson,
      uncertainty,
      citedUnresolvedInfluences,
      approvedNextObservation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExplainerOutput
    return ModelRuntimeApiPigeonUtils.deepEquals(this.summary, other.summary) && ModelRuntimeApiPigeonUtils.deepEquals(this.citedParagraphsJson, other.citedParagraphsJson) && ModelRuntimeApiPigeonUtils.deepEquals(this.uncertainty, other.uncertainty) && ModelRuntimeApiPigeonUtils.deepEquals(this.citedUnresolvedInfluences, other.citedUnresolvedInfluences) && ModelRuntimeApiPigeonUtils.deepEquals(this.approvedNextObservation, other.approvedNextObservation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.summary)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.citedParagraphsJson)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.uncertainty)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.citedUnresolvedInfluences)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.approvedNextObservation)
    return result
  }
  override fun toString(): String {
    return "ExplainerOutput(summary=$summary, citedParagraphsJson=$citedParagraphsJson, uncertainty=$uncertainty, citedUnresolvedInfluences=$citedUnresolvedInfluences, approvedNextObservation=$approvedNextObservation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModelRuntimeMetadata (
  val runtime: InferenceRuntime,
  val modelName: String,
  val promptVersion: Long,
  val outputGuardVersion: Long,
  val latencyMillis: Long,
  val schemaValid: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelRuntimeMetadata {
      val runtime = pigeonVar_list[0] as InferenceRuntime
      val modelName = pigeonVar_list[1] as String
      val promptVersion = pigeonVar_list[2] as Long
      val outputGuardVersion = pigeonVar_list[3] as Long
      val latencyMillis = pigeonVar_list[4] as Long
      val schemaValid = pigeonVar_list[5] as Boolean
      return ModelRuntimeMetadata(runtime, modelName, promptVersion, outputGuardVersion, latencyMillis, schemaValid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runtime,
      modelName,
      promptVersion,
      outputGuardVersion,
      latencyMillis,
      schemaValid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelRuntimeMetadata
    return ModelRuntimeApiPigeonUtils.deepEquals(this.runtime, other.runtime) && ModelRuntimeApiPigeonUtils.deepEquals(this.modelName, other.modelName) && ModelRuntimeApiPigeonUtils.deepEquals(this.promptVersion, other.promptVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.outputGuardVersion, other.outputGuardVersion) && ModelRuntimeApiPigeonUtils.deepEquals(this.latencyMillis, other.latencyMillis) && ModelRuntimeApiPigeonUtils.deepEquals(this.schemaValid, other.schemaValid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.runtime)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.modelName)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.promptVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.outputGuardVersion)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.latencyMillis)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.schemaValid)
    return result
  }
  override fun toString(): String {
    return "ModelRuntimeMetadata(runtime=$runtime, modelName=$modelName, promptVersion=$promptVersion, outputGuardVersion=$outputGuardVersion, latencyMillis=$latencyMillis, schemaValid=$schemaValid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModelExplainerResult (
  val output: ExplainerOutput? = null,
  val metadata: ModelRuntimeMetadata,
  val safety: SafetyResult,
  val failure: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelExplainerResult {
      val output = pigeonVar_list[0] as ExplainerOutput?
      val metadata = pigeonVar_list[1] as ModelRuntimeMetadata
      val safety = pigeonVar_list[2] as SafetyResult
      val failure = pigeonVar_list[3] as String?
      return ModelExplainerResult(output, metadata, safety, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      output,
      metadata,
      safety,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelExplainerResult
    return ModelRuntimeApiPigeonUtils.deepEquals(this.output, other.output) && ModelRuntimeApiPigeonUtils.deepEquals(this.metadata, other.metadata) && ModelRuntimeApiPigeonUtils.deepEquals(this.safety, other.safety) && ModelRuntimeApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.output)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.metadata)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.safety)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "ModelExplainerResult(output=$output, metadata=$metadata, safety=$safety, failure=$failure)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SafetyResult (
  val accepted: Boolean,
  val failures: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SafetyResult {
      val accepted = pigeonVar_list[0] as Boolean
      val failures = pigeonVar_list[1] as List<String>
      return SafetyResult(accepted, failures)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accepted,
      failures,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SafetyResult
    return ModelRuntimeApiPigeonUtils.deepEquals(this.accepted, other.accepted) && ModelRuntimeApiPigeonUtils.deepEquals(this.failures, other.failures)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + ModelRuntimeApiPigeonUtils.deepHash(this.failures)
    return result
  }
  override fun toString(): String {
    return "SafetyResult(accepted=$accepted, failures=$failures)"
  }
}
private open class ModelRuntimeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          InferenceRuntime.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplorerRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplorerDecision.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplainerRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExplainerOutput.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelRuntimeMetadata.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelExplainerResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SafetyResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InferenceRuntime -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ExplorerRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ExplorerDecision -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ExplainerRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ExplainerOutput -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ModelRuntimeMetadata -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ModelExplainerResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is SafetyResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ModelRuntimeApi {
  fun explain(request: ExplainerRequest, callback: (Result<ModelExplainerResult>) -> Unit)

  companion object {
    /** The codec used by ModelRuntimeApi. */
    val codec: MessageCodec<Any?> by lazy {
      ModelRuntimeApiPigeonCodec()
    }
    /** Sets up an instance of `ModelRuntimeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ModelRuntimeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.why_pulse.ModelRuntimeApi.explain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ExplainerRequest
            api.explain(requestArg) { result: Result<ModelExplainerResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelRuntimeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelRuntimeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
