// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vueniverse.vueniverse.modeldownload

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ModelDownloadApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ModelDownloadState(val raw: Int) {
  NOT_CONFIGURED(0),
  REQUIRES_CONSENT(1),
  QUEUED(2),
  DOWNLOADING(3),
  VERIFYING(4),
  AVAILABLE(5),
  FAILED(6),
  CANCELLED(7);

  companion object {
    fun ofRaw(raw: Int): ModelDownloadState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ModelDownloadStatus (
  val state: ModelDownloadState,
  val downloadedBytes: Long,
  val totalBytes: Long,
  /** A percentage in the inclusive range 0 through 100. */
  val progress: Double,
  val retryable: Boolean,
  val detail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelDownloadStatus {
      val state = pigeonVar_list[0] as ModelDownloadState
      val downloadedBytes = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      val progress = pigeonVar_list[3] as Double
      val retryable = pigeonVar_list[4] as Boolean
      val detail = pigeonVar_list[5] as String?
      return ModelDownloadStatus(state, downloadedBytes, totalBytes, progress, retryable, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      downloadedBytes,
      totalBytes,
      progress,
      retryable,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelDownloadStatus
    return ModelDownloadApiPigeonUtils.deepEquals(this.state, other.state) && ModelDownloadApiPigeonUtils.deepEquals(this.downloadedBytes, other.downloadedBytes) && ModelDownloadApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && ModelDownloadApiPigeonUtils.deepEquals(this.progress, other.progress) && ModelDownloadApiPigeonUtils.deepEquals(this.retryable, other.retryable) && ModelDownloadApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.state)
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.downloadedBytes)
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.progress)
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.retryable)
    result = 31 * result + ModelDownloadApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "ModelDownloadStatus(state=$state, downloadedBytes=$downloadedBytes, totalBytes=$totalBytes, progress=$progress, retryable=$retryable, detail=$detail)"
  }
}
private open class ModelDownloadApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ModelDownloadState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelDownloadStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ModelDownloadState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ModelDownloadStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ModelDownloadApi {
  fun inspectDownload(callback: (Result<ModelDownloadStatus>) -> Unit)
  fun acceptAndStart(callback: (Result<ModelDownloadStatus>) -> Unit)
  fun ensureScheduled(callback: (Result<ModelDownloadStatus>) -> Unit)
  fun retryDownload(callback: (Result<ModelDownloadStatus>) -> Unit)
  fun cancelDownload(callback: (Result<ModelDownloadStatus>) -> Unit)

  companion object {
    /** The codec used by ModelDownloadApi. */
    val codec: MessageCodec<Any?> by lazy {
      ModelDownloadApiPigeonCodec()
    }
    /** Sets up an instance of `ModelDownloadApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ModelDownloadApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.ModelDownloadApi.inspectDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.inspectDownload{ result: Result<ModelDownloadStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelDownloadApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelDownloadApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.ModelDownloadApi.acceptAndStart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.acceptAndStart{ result: Result<ModelDownloadStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelDownloadApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelDownloadApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.ModelDownloadApi.ensureScheduled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.ensureScheduled{ result: Result<ModelDownloadStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelDownloadApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelDownloadApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.ModelDownloadApi.retryDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.retryDownload{ result: Result<ModelDownloadStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelDownloadApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelDownloadApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.ModelDownloadApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelDownload{ result: Result<ModelDownloadStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ModelDownloadApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ModelDownloadApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
