// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vueniverse.vueniverse.sources

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SourceApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class SourcePlatformKind(val raw: Int) {
  HEALTH_CONNECT(0),
  CALENDAR(1);

  companion object {
    fun ofRaw(raw: Int): SourcePlatformKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class HealthDataType(val raw: Int) {
  HEART_RATE(0),
  SLEEP(1),
  STEPS(2),
  EXERCISE(3),
  ACTIVITY(4),
  HRV_RMSSD(5);

  companion object {
    fun ofRaw(raw: Int): HealthDataType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class HealthAvailabilityStatus(val raw: Int) {
  AVAILABLE(0),
  UPDATE_REQUIRED(1),
  UNAVAILABLE(2);

  companion object {
    fun ofRaw(raw: Int): HealthAvailabilityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativePermissionState(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  UNAVAILABLE(2);

  companion object {
    fun ofRaw(raw: Int): NativePermissionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeFeatureState (
  val name: String,
  val available: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFeatureState {
      val name = pigeonVar_list[0] as String
      val available = pigeonVar_list[1] as Boolean
      return NativeFeatureState(name, available)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      available,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeFeatureState
    return SourceApiPigeonUtils.deepEquals(this.name, other.name) && SourceApiPigeonUtils.deepEquals(this.available, other.available)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.name)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.available)
    return result
  }
  override fun toString(): String {
    return "NativeFeatureState(name=$name, available=$available)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthAvailability (
  val status: HealthAvailabilityStatus,
  val features: List<NativeFeatureState>,
  val providerPackage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthAvailability {
      val status = pigeonVar_list[0] as HealthAvailabilityStatus
      val features = pigeonVar_list[1] as List<NativeFeatureState>
      val providerPackage = pigeonVar_list[2] as String?
      return NativeHealthAvailability(status, features, providerPackage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      features,
      providerPackage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthAvailability
    return SourceApiPigeonUtils.deepEquals(this.status, other.status) && SourceApiPigeonUtils.deepEquals(this.features, other.features) && SourceApiPigeonUtils.deepEquals(this.providerPackage, other.providerPackage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.status)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.features)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.providerPackage)
    return result
  }
  override fun toString(): String {
    return "NativeHealthAvailability(status=$status, features=$features, providerPackage=$providerPackage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthPermission (
  val type: HealthDataType,
  val state: NativePermissionState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthPermission {
      val type = pigeonVar_list[0] as HealthDataType
      val state = pigeonVar_list[1] as NativePermissionState
      return NativeHealthPermission(type, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthPermission
    return SourceApiPigeonUtils.deepEquals(this.type, other.type) && SourceApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.type)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "NativeHealthPermission(type=$type, state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthPermissionSnapshot (
  val permissions: List<NativeHealthPermission>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthPermissionSnapshot {
      val permissions = pigeonVar_list[0] as List<NativeHealthPermission>
      return NativeHealthPermissionSnapshot(permissions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      permissions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthPermissionSnapshot
    return SourceApiPigeonUtils.deepEquals(this.permissions, other.permissions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.permissions)
    return result
  }
  override fun toString(): String {
    return "NativeHealthPermissionSnapshot(permissions=$permissions)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeSourceFailure (
  val code: String,
  val message: String,
  val retryable: Boolean,
  val openSettingsRecommended: Boolean,
  val retryAfterMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSourceFailure {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val retryable = pigeonVar_list[2] as Boolean
      val openSettingsRecommended = pigeonVar_list[3] as Boolean
      val retryAfterMillis = pigeonVar_list[4] as Long?
      return NativeSourceFailure(code, message, retryable, openSettingsRecommended, retryAfterMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      retryable,
      openSettingsRecommended,
      retryAfterMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSourceFailure
    return SourceApiPigeonUtils.deepEquals(this.code, other.code) && SourceApiPigeonUtils.deepEquals(this.message, other.message) && SourceApiPigeonUtils.deepEquals(this.retryable, other.retryable) && SourceApiPigeonUtils.deepEquals(this.openSettingsRecommended, other.openSettingsRecommended) && SourceApiPigeonUtils.deepEquals(this.retryAfterMillis, other.retryAfterMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.code)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.message)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.retryable)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.openSettingsRecommended)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.retryAfterMillis)
    return result
  }
  override fun toString(): String {
    return "NativeSourceFailure(code=$code, message=$message, retryable=$retryable, openSettingsRecommended=$openSettingsRecommended, retryAfterMillis=$retryAfterMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeNumericSample (
  val epochMillis: Long,
  val offsetMinutes: Long,
  val value: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeNumericSample {
      val epochMillis = pigeonVar_list[0] as Long
      val offsetMinutes = pigeonVar_list[1] as Long
      val value = pigeonVar_list[2] as Double
      return NativeNumericSample(epochMillis, offsetMinutes, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      epochMillis,
      offsetMinutes,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeNumericSample
    return SourceApiPigeonUtils.deepEquals(this.epochMillis, other.epochMillis) && SourceApiPigeonUtils.deepEquals(this.offsetMinutes, other.offsetMinutes) && SourceApiPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.epochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.offsetMinutes)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "NativeNumericSample(epochMillis=$epochMillis, offsetMinutes=$offsetMinutes, value=$value)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeIntervalSegment (
  val startEpochMillis: Long,
  val endEpochMillis: Long,
  val category: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeIntervalSegment {
      val startEpochMillis = pigeonVar_list[0] as Long
      val endEpochMillis = pigeonVar_list[1] as Long
      val category = pigeonVar_list[2] as String
      return NativeIntervalSegment(startEpochMillis, endEpochMillis, category)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startEpochMillis,
      endEpochMillis,
      category,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeIntervalSegment
    return SourceApiPigeonUtils.deepEquals(this.startEpochMillis, other.startEpochMillis) && SourceApiPigeonUtils.deepEquals(this.endEpochMillis, other.endEpochMillis) && SourceApiPigeonUtils.deepEquals(this.category, other.category)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.startEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.endEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.category)
    return result
  }
  override fun toString(): String {
    return "NativeIntervalSegment(startEpochMillis=$startEpochMillis, endEpochMillis=$endEpochMillis, category=$category)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthRecord (
  val id: String,
  val type: HealthDataType,
  val startEpochMillis: Long,
  val endEpochMillis: Long,
  val startOffsetMinutes: Long,
  val endOffsetMinutes: Long,
  val lastModifiedEpochMillis: Long,
  val samples: List<NativeNumericSample>,
  val segments: List<NativeIntervalSegment>,
  val value: Double? = null,
  val unit: String? = null,
  val category: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthRecord {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as HealthDataType
      val startEpochMillis = pigeonVar_list[2] as Long
      val endEpochMillis = pigeonVar_list[3] as Long
      val startOffsetMinutes = pigeonVar_list[4] as Long
      val endOffsetMinutes = pigeonVar_list[5] as Long
      val lastModifiedEpochMillis = pigeonVar_list[6] as Long
      val samples = pigeonVar_list[7] as List<NativeNumericSample>
      val segments = pigeonVar_list[8] as List<NativeIntervalSegment>
      val value = pigeonVar_list[9] as Double?
      val unit = pigeonVar_list[10] as String?
      val category = pigeonVar_list[11] as String?
      return NativeHealthRecord(id, type, startEpochMillis, endEpochMillis, startOffsetMinutes, endOffsetMinutes, lastModifiedEpochMillis, samples, segments, value, unit, category)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      startEpochMillis,
      endEpochMillis,
      startOffsetMinutes,
      endOffsetMinutes,
      lastModifiedEpochMillis,
      samples,
      segments,
      value,
      unit,
      category,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthRecord
    return SourceApiPigeonUtils.deepEquals(this.id, other.id) && SourceApiPigeonUtils.deepEquals(this.type, other.type) && SourceApiPigeonUtils.deepEquals(this.startEpochMillis, other.startEpochMillis) && SourceApiPigeonUtils.deepEquals(this.endEpochMillis, other.endEpochMillis) && SourceApiPigeonUtils.deepEquals(this.startOffsetMinutes, other.startOffsetMinutes) && SourceApiPigeonUtils.deepEquals(this.endOffsetMinutes, other.endOffsetMinutes) && SourceApiPigeonUtils.deepEquals(this.lastModifiedEpochMillis, other.lastModifiedEpochMillis) && SourceApiPigeonUtils.deepEquals(this.samples, other.samples) && SourceApiPigeonUtils.deepEquals(this.segments, other.segments) && SourceApiPigeonUtils.deepEquals(this.value, other.value) && SourceApiPigeonUtils.deepEquals(this.unit, other.unit) && SourceApiPigeonUtils.deepEquals(this.category, other.category)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.id)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.type)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.startEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.endEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.startOffsetMinutes)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.endOffsetMinutes)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.lastModifiedEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.samples)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.segments)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.value)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.unit)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.category)
    return result
  }
  override fun toString(): String {
    return "NativeHealthRecord(id=$id, type=$type, startEpochMillis=$startEpochMillis, endEpochMillis=$endEpochMillis, startOffsetMinutes=$startOffsetMinutes, endOffsetMinutes=$endOffsetMinutes, lastModifiedEpochMillis=$lastModifiedEpochMillis, samples=$samples, segments=$segments, value=$value, unit=$unit, category=$category)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthPage (
  val records: List<NativeHealthRecord>,
  val nextPageToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthPage {
      val records = pigeonVar_list[0] as List<NativeHealthRecord>
      val nextPageToken = pigeonVar_list[1] as String?
      return NativeHealthPage(records, nextPageToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      records,
      nextPageToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthPage
    return SourceApiPigeonUtils.deepEquals(this.records, other.records) && SourceApiPigeonUtils.deepEquals(this.nextPageToken, other.nextPageToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.records)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.nextPageToken)
    return result
  }
  override fun toString(): String {
    return "NativeHealthPage(records=$records, nextPageToken=$nextPageToken)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthPageResult (
  val page: NativeHealthPage? = null,
  val failure: NativeSourceFailure? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthPageResult {
      val page = pigeonVar_list[0] as NativeHealthPage?
      val failure = pigeonVar_list[1] as NativeSourceFailure?
      return NativeHealthPageResult(page, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      page,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthPageResult
    return SourceApiPigeonUtils.deepEquals(this.page, other.page) && SourceApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.page)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "NativeHealthPageResult(page=$page, failure=$failure)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthChanges (
  val upserts: List<NativeHealthRecord>,
  val deletedRecordIds: List<String>,
  val nextChangesToken: String,
  val hasMore: Boolean,
  val tokenExpired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthChanges {
      val upserts = pigeonVar_list[0] as List<NativeHealthRecord>
      val deletedRecordIds = pigeonVar_list[1] as List<String>
      val nextChangesToken = pigeonVar_list[2] as String
      val hasMore = pigeonVar_list[3] as Boolean
      val tokenExpired = pigeonVar_list[4] as Boolean
      return NativeHealthChanges(upserts, deletedRecordIds, nextChangesToken, hasMore, tokenExpired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      upserts,
      deletedRecordIds,
      nextChangesToken,
      hasMore,
      tokenExpired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthChanges
    return SourceApiPigeonUtils.deepEquals(this.upserts, other.upserts) && SourceApiPigeonUtils.deepEquals(this.deletedRecordIds, other.deletedRecordIds) && SourceApiPigeonUtils.deepEquals(this.nextChangesToken, other.nextChangesToken) && SourceApiPigeonUtils.deepEquals(this.hasMore, other.hasMore) && SourceApiPigeonUtils.deepEquals(this.tokenExpired, other.tokenExpired)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.upserts)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.deletedRecordIds)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.nextChangesToken)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.hasMore)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.tokenExpired)
    return result
  }
  override fun toString(): String {
    return "NativeHealthChanges(upserts=$upserts, deletedRecordIds=$deletedRecordIds, nextChangesToken=$nextChangesToken, hasMore=$hasMore, tokenExpired=$tokenExpired)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthChangesResult (
  val changes: NativeHealthChanges? = null,
  val failure: NativeSourceFailure? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthChangesResult {
      val changes = pigeonVar_list[0] as NativeHealthChanges?
      val failure = pigeonVar_list[1] as NativeSourceFailure?
      return NativeHealthChangesResult(changes, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      changes,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthChangesResult
    return SourceApiPigeonUtils.deepEquals(this.changes, other.changes) && SourceApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.changes)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "NativeHealthChangesResult(changes=$changes, failure=$failure)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHealthTokenResult (
  val token: String? = null,
  val failure: NativeSourceFailure? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHealthTokenResult {
      val token = pigeonVar_list[0] as String?
      val failure = pigeonVar_list[1] as NativeSourceFailure?
      return NativeHealthTokenResult(token, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      token,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHealthTokenResult
    return SourceApiPigeonUtils.deepEquals(this.token, other.token) && SourceApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.token)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "NativeHealthTokenResult(token=$token, failure=$failure)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCalendarPermissionSnapshot (
  val state: NativePermissionState,
  val shouldShowRationale: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCalendarPermissionSnapshot {
      val state = pigeonVar_list[0] as NativePermissionState
      val shouldShowRationale = pigeonVar_list[1] as Boolean
      return NativeCalendarPermissionSnapshot(state, shouldShowRationale)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      shouldShowRationale,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCalendarPermissionSnapshot
    return SourceApiPigeonUtils.deepEquals(this.state, other.state) && SourceApiPigeonUtils.deepEquals(this.shouldShowRationale, other.shouldShowRationale)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.state)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.shouldShowRationale)
    return result
  }
  override fun toString(): String {
    return "NativeCalendarPermissionSnapshot(state=$state, shouldShowRationale=$shouldShowRationale)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCalendarSeries (
  val id: String,
  val title: String,
  val recurrenceRule: String,
  val timeZone: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCalendarSeries {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val recurrenceRule = pigeonVar_list[2] as String
      val timeZone = pigeonVar_list[3] as String
      return NativeCalendarSeries(id, title, recurrenceRule, timeZone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      recurrenceRule,
      timeZone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCalendarSeries
    return SourceApiPigeonUtils.deepEquals(this.id, other.id) && SourceApiPigeonUtils.deepEquals(this.title, other.title) && SourceApiPigeonUtils.deepEquals(this.recurrenceRule, other.recurrenceRule) && SourceApiPigeonUtils.deepEquals(this.timeZone, other.timeZone)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.id)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.title)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.recurrenceRule)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.timeZone)
    return result
  }
  override fun toString(): String {
    return "NativeCalendarSeries(id=$id, title=$title, recurrenceRule=$recurrenceRule, timeZone=$timeZone)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCalendarDiscoveryResult (
  val series: List<NativeCalendarSeries>,
  val failure: NativeSourceFailure? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCalendarDiscoveryResult {
      val series = pigeonVar_list[0] as List<NativeCalendarSeries>
      val failure = pigeonVar_list[1] as NativeSourceFailure?
      return NativeCalendarDiscoveryResult(series, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      series,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCalendarDiscoveryResult
    return SourceApiPigeonUtils.deepEquals(this.series, other.series) && SourceApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.series)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "NativeCalendarDiscoveryResult(series=$series, failure=$failure)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCalendarInstance (
  val instanceId: String,
  val seriesId: String,
  val startEpochMillis: Long,
  val endEpochMillis: Long,
  val offsetMinutes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCalendarInstance {
      val instanceId = pigeonVar_list[0] as String
      val seriesId = pigeonVar_list[1] as String
      val startEpochMillis = pigeonVar_list[2] as Long
      val endEpochMillis = pigeonVar_list[3] as Long
      val offsetMinutes = pigeonVar_list[4] as Long
      return NativeCalendarInstance(instanceId, seriesId, startEpochMillis, endEpochMillis, offsetMinutes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instanceId,
      seriesId,
      startEpochMillis,
      endEpochMillis,
      offsetMinutes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCalendarInstance
    return SourceApiPigeonUtils.deepEquals(this.instanceId, other.instanceId) && SourceApiPigeonUtils.deepEquals(this.seriesId, other.seriesId) && SourceApiPigeonUtils.deepEquals(this.startEpochMillis, other.startEpochMillis) && SourceApiPigeonUtils.deepEquals(this.endEpochMillis, other.endEpochMillis) && SourceApiPigeonUtils.deepEquals(this.offsetMinutes, other.offsetMinutes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.instanceId)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.seriesId)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.startEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.endEpochMillis)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.offsetMinutes)
    return result
  }
  override fun toString(): String {
    return "NativeCalendarInstance(instanceId=$instanceId, seriesId=$seriesId, startEpochMillis=$startEpochMillis, endEpochMillis=$endEpochMillis, offsetMinutes=$offsetMinutes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCalendarSnapshotResult (
  val instances: List<NativeCalendarInstance>,
  val complete: Boolean,
  val failure: NativeSourceFailure? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCalendarSnapshotResult {
      val instances = pigeonVar_list[0] as List<NativeCalendarInstance>
      val complete = pigeonVar_list[1] as Boolean
      val failure = pigeonVar_list[2] as NativeSourceFailure?
      return NativeCalendarSnapshotResult(instances, complete, failure)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instances,
      complete,
      failure,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCalendarSnapshotResult
    return SourceApiPigeonUtils.deepEquals(this.instances, other.instances) && SourceApiPigeonUtils.deepEquals(this.complete, other.complete) && SourceApiPigeonUtils.deepEquals(this.failure, other.failure)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.instances)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.complete)
    result = 31 * result + SourceApiPigeonUtils.deepHash(this.failure)
    return result
  }
  override fun toString(): String {
    return "NativeCalendarSnapshotResult(instances=$instances, complete=$complete, failure=$failure)"
  }
}
private open class SourceApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourcePlatformKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HealthDataType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HealthAvailabilityStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativePermissionState.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFeatureState.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthAvailability.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthPermission.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthPermissionSnapshot.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSourceFailure.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeNumericSample.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeIntervalSegment.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthRecord.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthPage.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthPageResult.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthChanges.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthChangesResult.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHealthTokenResult.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCalendarPermissionSnapshot.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCalendarSeries.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCalendarDiscoveryResult.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCalendarInstance.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCalendarSnapshotResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourcePlatformKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HealthDataType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is HealthAvailabilityStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NativePermissionState -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is NativeFeatureState -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeHealthAvailability -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeHealthPermission -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeHealthPermissionSnapshot -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NativeSourceFailure -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is NativeNumericSample -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is NativeIntervalSegment -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is NativeHealthRecord -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is NativeHealthPage -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is NativeHealthPageResult -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is NativeHealthChanges -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is NativeHealthChangesResult -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is NativeHealthTokenResult -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is NativeCalendarPermissionSnapshot -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is NativeCalendarSeries -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is NativeCalendarDiscoveryResult -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is NativeCalendarInstance -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is NativeCalendarSnapshotResult -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SourceApi {
  fun getHealthAvailability(callback: (Result<NativeHealthAvailability>) -> Unit)
  fun getHealthPermissionSnapshot(callback: (Result<NativeHealthPermissionSnapshot>) -> Unit)
  fun requestHealthPermissions(types: List<HealthDataType>, callback: (Result<NativeHealthPermissionSnapshot>) -> Unit)
  fun readHealthPage(type: HealthDataType, startEpochMillis: Long, endEpochMillis: Long, pageToken: String?, pageSize: Long, callback: (Result<NativeHealthPageResult>) -> Unit)
  fun createHealthChangesToken(type: HealthDataType, callback: (Result<NativeHealthTokenResult>) -> Unit)
  fun readHealthChanges(type: HealthDataType, changesToken: String, callback: (Result<NativeHealthChangesResult>) -> Unit)
  fun getCalendarPermissionSnapshot(): NativeCalendarPermissionSnapshot
  fun requestCalendarPermission(callback: (Result<NativeCalendarPermissionSnapshot>) -> Unit)
  fun discoverRecurringCalendarSeries(callback: (Result<NativeCalendarDiscoveryResult>) -> Unit)
  fun readRecurringCalendarSnapshot(startEpochMillis: Long, endEpochMillis: Long, callback: (Result<NativeCalendarSnapshotResult>) -> Unit)
  fun openSourceSettings(kind: SourcePlatformKind)

  companion object {
    /** The codec used by SourceApi. */
    val codec: MessageCodec<Any?> by lazy {
      SourceApiPigeonCodec()
    }
    /** Sets up an instance of `SourceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SourceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.getHealthAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getHealthAvailability{ result: Result<NativeHealthAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.getHealthPermissionSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getHealthPermissionSnapshot{ result: Result<NativeHealthPermissionSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.requestHealthPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typesArg = args[0] as List<HealthDataType>
            api.requestHealthPermissions(typesArg) { result: Result<NativeHealthPermissionSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.readHealthPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as HealthDataType
            val startEpochMillisArg = args[1] as Long
            val endEpochMillisArg = args[2] as Long
            val pageTokenArg = args[3] as String?
            val pageSizeArg = args[4] as Long
            api.readHealthPage(typeArg, startEpochMillisArg, endEpochMillisArg, pageTokenArg, pageSizeArg) { result: Result<NativeHealthPageResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.createHealthChangesToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as HealthDataType
            api.createHealthChangesToken(typeArg) { result: Result<NativeHealthTokenResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.readHealthChanges$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as HealthDataType
            val changesTokenArg = args[1] as String
            api.readHealthChanges(typeArg, changesTokenArg) { result: Result<NativeHealthChangesResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.getCalendarPermissionSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCalendarPermissionSnapshot())
            } catch (exception: Throwable) {
              SourceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.requestCalendarPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestCalendarPermission{ result: Result<NativeCalendarPermissionSnapshot> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.discoverRecurringCalendarSeries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.discoverRecurringCalendarSeries{ result: Result<NativeCalendarDiscoveryResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.readRecurringCalendarSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMillisArg = args[0] as Long
            val endEpochMillisArg = args[1] as Long
            api.readRecurringCalendarSnapshot(startEpochMillisArg, endEpochMillisArg) { result: Result<NativeCalendarSnapshotResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SourceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SourceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vueniverse.SourceApi.openSourceSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kindArg = args[0] as SourcePlatformKind
            val wrapped: List<Any?> = try {
              api.openSourceSettings(kindArg)
              listOf(null)
            } catch (exception: Throwable) {
              SourceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
